#!/usr/bin/env python3
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) Kleinrotti <kleinrotti@saltcloud.de>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.


def agent_telematik_konnektor_arguments(params, hostname, ipaddress):
    args = []
    args += ['-u', ipaddress or hostname]
    args += ['-p', params['port']]
    args += ['-m', params['mandant']]
    args += ['-c', params['clientsystem']]
    args += ['-w', params['workplace']]
    if "verify_ssl" in params:
        args += ['--ssl_verify']
    if "client_auth" in params:
        if "cert_auth" in params["client_auth"]:
            args += ['-cert', params["client_auth"][1]["client_cert"]]
            args += ['-certkey', params["client_auth"][1]["client_priv_key"]]
        elif "basic_auth" in params["client_auth"]:
            args += ['-username', params["client_auth"][1]["username"]]
            args += ['-password', params["client_auth"][1]["password"]]
    if "mandant_wide" in params:
        args += ['--mandant_wide']
    return args


special_agent_info['telematik_konnektor'] = agent_telematik_konnektor_arguments
