name: build-release

on:
  push:
    tags:
    - '*.*.*'

jobs:
  build-release:
    name: Build Release Package
    runs-on: ubuntu-latest
    container:
      image: checkmk/check-mk-raw:2.4.0-latest

    env:
      OMD_ROOT: /omd/sites/cmk
      OMD_SITE: cmk
      CMK_SITE_ID: cmk
      WORKSPACE: ${{ github.workspace }}

    steps:
      - name: Initialize Checkmk Site
        run: /docker-entrypoint.sh /bin/true
      - uses: actions/checkout@v2
      - name: Set version env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set current release version
        run: sed -i 's#0.0.0#${{ env.RELEASE_VERSION }}#' src/package
      - name: Setup links
        run: .devcontainer/symlink.sh
      - name: Update GITHUB_PATH
        run: echo "/omd/sites/cmk/bin" >> $GITHUB_PATH
      - name: Build Extension
        run: .devcontainer/build.sh

      - name: Release files
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: false
          fail_on_unmatched_files: true
          files: |
              telematik_konnektor-${{ env.RELEASE_VERSION }}.mkp